title: Algorithm Grounds
description: Long Form Jekyll theme built with SASS / COMPASS / SUSY

url: http://lsg154.github.io
baseurl: ""
paginate_path: "post/page:num/"
permalink: post/:title/

markdown: redcarpet
highlighter: pygments
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Post
   url: /post
 - title: Compiler
   url: /post

[Compiler]: www.naver.com
